<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NAudio.Midi">
      <HintPath>..\3rdParty\NAudio\NAudio.Midi.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.WinMM">
      <HintPath>..\3rdParty\NAudio\NAudio.WinMM.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
