name: ReBuzz Native Machines Build

on:
  workflow_dispatch:

jobs:
  native-build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Native Machines
      run: msbuild NativeMachines/NativeMachines.sln /p:Configuration=Release

    - name: Upload native artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rebuzz-native-machines
        path: NativeMachines/bin/Release/
